const EDIT_BOXES = "EDIT_BOXES";
const RESET_GAME = "RESET_GAME";
const CHANGE_PLAYER = "CHANGE_PLAYER";
const VALIDATE_WINNER = "VALIDATE_WINNER";
const FINISH_GAME = "FINISH_GAME";

export { EDIT_BOXES, RESET_GAME, CHANGE_PLAYER, VALIDATE_WINNER, FINISH_GAME };
